---
  - name: installing base packages
    yum: name={{ item }} state=present
    with_items:
      - bpg-sans-fonts
      - bpg-serif-fonts
      - bzip2
      - cjkuni-fonts-common
      - cjkuni-ukai-fonts
      - cjkuni-uming-fonts
      - curl
      - dbus
      - dejavu-fonts-common
      - dejavu-sans-mono-fonts
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - fontpackages-tools
      - gawk
      - git
      - mailx
      - ImageMagick
      - iotop
      - libaio-devel
      - liberation-fonts-common
      - lohit-bengali-fonts
      - lohit-devanagari-fonts
      - lohit-gujarati-fonts
      - lohit-kannada-fonts
      - lohit-malayalam-fonts
      - lohit-oriya-fonts
      - lohit-punjabi-fonts
      - lohit-tamil-fonts
      - lohit-telugu-fonts
      - man
      - perl-DBI
      - libicu-devel
      - perl-NetAddr-IP 
      - perl-SNMP_Session
      - nc
      - ntp
      - python-configobj
      - openssh-clients
      - tcpdump
      - unzip
      - vim-minimal
      - zip

  - name: install symmetrics repo
    yum: name={{ files_url }}/centos/base/symmetrics-repo-1.0-1.x86_64.rpm state=present

  - name: install custom kernel
    yum: name=symmetrics-kernel state=present
    
  - name: install zfs utilities
    yum: name=zfs state=present

  - name: install gpt fdisk utilities
    yum: name=gdisk state=present

  - name: change hostname
    lineinfile: dest=/etc/sysconfig/network regexp=^HOSTNAME=.* line=HOSTNAME={{ name }}

  - name: change 127.0.1.1 to match hostname
    lineinfile: dest=/etc/hosts regexp=^127\.0\.1\.1 line="127.0.1.1 {{ name }}"
  
  - name: reboot remote node to pick up new kernel
    command: shutdown -r now

  - name: wait for machine to come back
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=15 timeout=300

  - name: ensure /indicee exists
    file: path=/indicee state=directory

  - name: create lvm slice for zfs pool
    lvol: vg={{ vg }} lv=zfs size={{ zfs_size }}

  - name: create zfs pool on lvm
    command: zpool create -f zfs /dev/mapper/{{ vg }}-zfs creates=/zfs

  - name: create /indicee/log file system with compression
    zfs: name=zfs/log compression=on atime=off mountpoint=/indicee/log state=present

  - name: ensure zfs added to startup
    command: chkconfig zfs on

  - name: create logical volume for staging db
    lvol: vg={{ vg }} lv={{ staging_lv }} size={{ staging_mount_size }}

  - name: check if the staging db file system is mounted
    shell: grep {{ staging_lv }} /proc/mounts
    register: filesystem
    ignore_errors: True

  - name: format staging db lv as ext4
    shell: mkfs.ext4 -L {{ staging_mount }} -m 0 /dev/mapper/{{ vg }}-{{ staging_lv }}
    when: filesystem|failed

  - name: ensure /indicee/{{ staging_mount }} exists
    file: path=/indicee/{{ staging_mount }} state=directory

  - name: mount staging db file system
    mount: name=/indicee/{{ staging_mount }} src='LABEL={{ staging_mount }}' fstype=ext4 opts='noatime' state=mounted
    when: filesystem|failed

  - name: ensure /indicee/bin exists
    file: path=/indicee/bin state=directory
