---
  - name: install postgresql repo
    yum: name=http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/pgdg-centos92-9.2-6.noarch.rpm state=present

  - name: install postgresql-9.2
    yum: name={{ item }} state=present
    with_items:
      - postgresql92
      - postgresql92-contrib
      - postgresql92-server

  - name: update shmmax sysctl parameter
    sysctl: name=kernel.shmmax value=40000000000 state=present

  - name: update shmall sysctl parameter
    sysctl: name=kernel.shmall value=40000000000 state=present

  - name: update shmmni sysctl parameter
    sysctl: name=kernel.shmmni value=1345294336 state=present
  
  - name: ensure /indicee/postgresql-data/9.2 exists
    file: state=directory path=/indicee/postgresql-data/9.2 owner=postgres group=postgres mode=2770

  - name: ensure postgresql db log directory exists
    file: state=directory path=/indicee/postgresql-data/log owner=postgres group=postgres mode=2770

  - name: ensure /indicee/postgresql-data/9.2/data exists
    file: state=directory path=/indicee/postgresql-data/9.2/data owner=postgres group=postgres mode=2700

  - name: ensure /indicee/postgresql-data/9.2/backup exists
    file: state=directory path=/indicee/postgresql-data/9.2/backups owner=postgres group=postgres mode=2700

  - name: install postgresql-9.2 init script
    template: src=postgresql-9.2.init.j2 dest=/etc/init.d/postgresql-9.2 mode=0755

  - name: initialize the postgresql db
    command: service postgresql-9.2 initdb creates=/indicee/postgresql-data/9.2/data/PG_VERSION
  
  - name: install the postgresql.conf
    template: src=postgresql.conf.j2 dest=/indicee/postgresql-data/9.2/data/postgresql.conf mode=0640 owner=postgres group=postgres

  - name: install the pg_hba.conf
    template: src=pg_hba.conf.j2 dest=/indicee/postgresql-data/9.2/data/pg_hba.conf mode=0640 owner=postgres group=postgres

  - name: restart postgresql-9.2
    command: service postgresql-9.2 restart
