---
  - name: put add_postgresql_repo
    template: src=add_postgresql_repo.j2 dest=/tmp/add_postgresql_repo mode=0755 

  - name: add postgresql repository
    command: /tmp/add_postgresql_repo

  - name: update apt cache
    apt: update-cache=yes

  - name: install postgresql-9.2
    apt: pkg=postgresql-9.2 state=present

  - name: install postgresql-9.2 contrib extensions
    apt: pkg=postgresql-contrib-9.2 state=present

  - name: stop postgresql-9.2
    command: /etc/init.d/postgresql stop

  - name: update shmmax sysctl parameter
    sysctl: name=kernel.shmmax value=40000000000 state=present

  - name: update shmall sysctl parameter
    sysctl: name=kernel.shmall value=40000000000 state=present

  - name: update shmmni sysctl parameter
    sysctl: name=kernel.shmmni value=1345294336 state=present

  - name: install the postgresql.conf
    template: src=postgresql.conf.j2 dest=/etc/postgresql/9.2/main/postgresql.conf mode=0644 owner=postgres group=postgres mode=0644

  - name: install the pg_hba.conf
    template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.2/main/pg_hba.conf mode=0644 owner=postgres group=postgres mode=0644

  - name: ensure /indicee/postgresql-data/9.2 exists
    file: state=directory path=/indicee/postgresql-data/9.2 owner=postgres group=postgres mode=2770

  - name: ensure postgresql db log directory exists
    file: state=directory path=/indicee/postgresql-data/log owner=postgres group=postgres mode=2770
    
  - name: move /var/lib/postgresql/9.2/main to /indicee/postgresql-data/9.2/main
    command: mv /var/lib/postgresql/9.2/main /indicee/postgresql-data/9.2/main creates=/indicee/postgresql-data/9.2/main

  - name: start postgresql
    command: service postgresql start
