---
  - name: start supervisor
    action: service name=supervisor state=started enabled=yes

  - name: restart supervisor
    action: service name=supervisor state=restarted enabled=yes

  - name: stop supervisor
    action: service name=supervisor state=stopped enabled=yes
