---
  - name: ensure /indicee/mysql-data exists
    file: state=directory path=/indicee/mysql-data owner=mysql group=mysql mode=2770

  - name: ensure percona db data directory exists
    file: state=directory path=/indicee/mysql-data/db owner=mysql group=mysql mode=2770

  - name: ensure percona db log directory exists
    file: state=directory path=/indicee/mysql-data/log owner=mysql group=mysql mode=2770
    
  - name: put add_percona_repo
    copy: src=add_percona_repo dest=/tmp/add_percona_repo mode=0755 

  - name: add percona repository
    command: add_percona_repo chdir=/tmp creates=/tmp/add_percona_repo

  - name: update apt cache
    apt: update-cache=yes

  - name: install libdbd-mysql-perl
    apt: pkg=libdbd-mysql-perl state=present

  - name: install libmysqlclient18
    apt: pkg=libmysqlclient18 state=present

  - name: install percona-xtrabackup
    apt: pkg=percona-xtrabackup state=present

  - name: install percona-xtradb-cluster-client-5.5
    apt: pkg=percona-xtradb-cluster-client-5.5 state=present

  - name: install percona-xtradb-cluster-common-5.5
    apt: pkg=percona-xtradb-cluster-common-5.5 state=present

  - name: install percona-xtradb-cluster-galera-2.x
    apt: pkg=percona-xtradb-cluster-galera-2.x state=present

  - name: install percona-xtradb-cluster-server-5.5
    apt: pkg=percona-xtradb-cluster-server-5.5 state=present

  - name: install the my.cnf
    copy: src=my.cnf dest=/etc/mysql/my.cnf mode=0644

  - name: install base percona files
    command: /usr/bin/mysql_install_db creates=/indicee/mysql-data/db/mysql
    notify:
      - start percona
