---
  - name: install nginx repo
    yum: name=nginx-repo state=present

  - name: install nginx
    yum: name=nginx state=present

  - name: disable nginx from init.d
    command: chkconfig nginx off
