---

  - name: ensure /indicee exists
    file: state=directory path=/indicee

  - name: ensure /indicee/bin exists
    file: path=/indicee/bin state=directory

  - name: ensure /indicee/svc exists
    file: path=/indicee/svc state=directory

  - name: ensure /indicee/log exists
    file: path=/indicee/log state=directory

  - name: install python-apt
    raw: "apt-get install -y python-apt"

  - name: update apt cache
    apt: update-cache=yes

  - name: installing base packages
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - daemontools
      - daemontools-run
      - dbus
      - gawk
      - git
      - heirloom-mailx
      - imagemagick
      - iotop
      - jed
      - libaio1
      - libcache-perl
      - libdbi-perl
      - libio-multiplex-perl
      - libipc-sharelite-perl
      - libnet-cidr-perl
      - libnet-snmp-perl
      - libopts25
      - libpcap0.8
      - munin-common
      - munin-node
      - munin-plugins-extra
      - netcat-openbsd
      - nload
      - ntp
      - python-configobj
      - python-psutil
      - screen
      - ssh
      - sudo
      - tcpdump
      - unzip
      - vim
      - zip
