---
  - name: copy add_squeeze_backports_repo
    get_url: url=http://bastion.symmetrics.local/collectd/add_squeeze_backports_repo dest=/tmp/add_squeeze_backports_repo mode=0755 force=yes
    when_string: '"squeeze" in "${ansible_lsb.codename}"'

  - name: add squeeze_backports
    command: /tmp/add_squeeze_backports_repo
    when_string: '"squeeze" in "${ansible_lsb.codename}"'

  - name: update apt cache
    apt: update-cache=yes
    when_string: '"squeeze" in "${ansible_lsb.codename}"'

  - name: install collectd
    apt: pkg=collectd-core=5.1.0-3~bpo60+2 state=present
    when_string: '"squeeze" in "${ansible_lsb.codename}"'

  - name: install collectd
    apt: pkg=collectd state=present
    when_string: '"wheezy" in "${ansible_lsb.codename}"'

  - name: remove collectd from init and stop currently running instance
    shell: service collectd stop && update-rc.d -f collectd remove 

  - name: install collectd.conf
    template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf mode=0644

  - name: install collectd supervisor conf
    get_url: url=http://bastion.symmetrics.local/collectd/collectd.conf dest=/etc/supervisor/conf.d/collectd.conf mode=0644 force=yes

  - name: start collectd
    command: supervisorctl reload
