---
  - name: copy add_squeeze_backports_repo
    get_url: url={{ files_url }}/collectd/add_squeeze_backports_repo dest=/tmp/add_squeeze_backports_repo mode=0755 force=yes

  - name: add squeeze_backports
    command: /tmp/add_squeeze_backports_repo

  - name: update apt cache
    apt: update-cache=yes

  - name: install collectd
    apt: pkg=collectd-core=5.1.0-3~bpo60+2 state=present

  - name: remove collectd from init and stop currently running instance
    shell: service collectd stop && update-rc.d -f collectd remove 

  - name: install collectd.conf
    template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf mode=0644

  - name: install collectd supervisor conf
    get_url: url={{ files_url }}/collectd/collectd.conf dest=/etc/supervisor/conf.d/collectd.conf mode=0644 force=yes
